FROM payara/server-full:173

# Setup configuration
USER payara
#RUN changeConfigDBProd.sh
COPY postgresql-42.2.24.jar /opt/payara41/glassfish/domains/domain1/lib
COPY domain.xml /opt/payara41/glassfish/domains/domain1/config